server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.96.138.34:3306/dianping?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 15521092385l
  redis:
    host: 47.96.138.34
    port: 6379
    password: syf133618
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug